param(
    [string]$Server = "localhost,1433",
    [string]$Database = "fashion_shop",
    [string]$Username = "sa",
    [string]$Password = $(if ($env:DB_PASSWORD) { $env:DB_PASSWORD } else { "123456" }),
    [string]$OutputPath = (Join-Path $PSScriptRoot "schema.dbml")
)

$ErrorActionPreference = "Stop"

function Convert-SqlTypeToDbml {
    param($Row)

    $type = [string]$Row.type_name
    switch ($type.ToLowerInvariant()) {
        { $_ -in @("nvarchar", "nchar") } {
            $length = if ($Row.max_length -eq -1) { "max" } else { [int]$Row.max_length / 2 }
            return "$type($length)"
        }
        { $_ -in @("varchar", "char", "varbinary", "binary") } {
            $length = if ($Row.max_length -eq -1) { "max" } else { [int]$Row.max_length }
            return "$type($length)"
        }
        { $_ -in @("decimal", "numeric") } {
            return "$type($($Row.precision),$($Row.scale))"
        }
        { $_ -in @("datetime2", "datetimeoffset", "time") } {
            if ([int]$Row.scale -eq 7) {
                return $type
            }
            return "$type($($Row.scale))"
        }
        default { return $type }
    }
}

$connectionString = "Server=$Server;Database=$Database;User ID=$Username;Password=$Password;Encrypt=True;TrustServerCertificate=True;"
$connection = [System.Data.SqlClient.SqlConnection]::new($connectionString)
$connection.Open()

try {
    $columnSql = @"
SELECT
    s.name AS schema_name,
    t.name AS table_name,
    c.column_id,
    c.name AS column_name,
    ty.name AS type_name,
    c.max_length,
    c.precision,
    c.scale,
    c.is_nullable,
    c.is_identity,
    dc.definition AS default_definition,
    CASE WHEN pk.column_id IS NULL THEN 0 ELSE 1 END AS is_primary_key,
    CASE WHEN uq.column_id IS NULL THEN 0 ELSE 1 END AS is_single_unique
FROM sys.tables t
JOIN sys.schemas s ON s.schema_id = t.schema_id
JOIN sys.columns c ON c.object_id = t.object_id
JOIN sys.types ty ON ty.user_type_id = c.user_type_id
LEFT JOIN sys.default_constraints dc
    ON dc.parent_object_id = c.object_id AND dc.parent_column_id = c.column_id
LEFT JOIN (
    SELECT ic.object_id, ic.column_id
    FROM sys.indexes i
    JOIN sys.index_columns ic ON ic.object_id = i.object_id AND ic.index_id = i.index_id
    WHERE i.is_primary_key = 1
) pk ON pk.object_id = c.object_id AND pk.column_id = c.column_id
LEFT JOIN (
    SELECT ic.object_id, ic.column_id
    FROM sys.indexes i
    JOIN sys.index_columns ic ON ic.object_id = i.object_id AND ic.index_id = i.index_id
    WHERE i.is_unique = 1
      AND i.is_primary_key = 0
      AND 1 = (SELECT COUNT(*) FROM sys.index_columns x
               WHERE x.object_id = i.object_id AND x.index_id = i.index_id AND x.key_ordinal > 0)
) uq ON uq.object_id = c.object_id AND uq.column_id = c.column_id
WHERE t.is_ms_shipped = 0
ORDER BY s.name, t.name, c.column_id;
"@

    $foreignKeySql = @"
SELECT
    fk.name AS fk_name,
    sch_child.name AS child_schema,
    tab_child.name AS child_table,
    col_child.name AS child_column,
    sch_parent.name AS parent_schema,
    tab_parent.name AS parent_table,
    col_parent.name AS parent_column,
    fk.delete_referential_action_desc AS delete_action
FROM sys.foreign_keys fk
JOIN sys.foreign_key_columns fkc ON fkc.constraint_object_id = fk.object_id
JOIN sys.tables tab_child ON tab_child.object_id = fk.parent_object_id
JOIN sys.schemas sch_child ON sch_child.schema_id = tab_child.schema_id
JOIN sys.columns col_child ON col_child.object_id = tab_child.object_id AND col_child.column_id = fkc.parent_column_id
JOIN sys.tables tab_parent ON tab_parent.object_id = fk.referenced_object_id
JOIN sys.schemas sch_parent ON sch_parent.schema_id = tab_parent.schema_id
JOIN sys.columns col_parent ON col_parent.object_id = tab_parent.object_id AND col_parent.column_id = fkc.referenced_column_id
WHERE tab_child.is_ms_shipped = 0
ORDER BY fk.name, fkc.constraint_column_id;
"@

    $adapter = [System.Data.SqlClient.SqlDataAdapter]::new($columnSql, $connection)
    $columns = [System.Data.DataTable]::new()
    [void]$adapter.Fill($columns)

    $adapter = [System.Data.SqlClient.SqlDataAdapter]::new($foreignKeySql, $connection)
    $foreignKeys = [System.Data.DataTable]::new()
    [void]$adapter.Fill($foreignKeys)

    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add("// Generated from SQL Server metadata. Do not edit this file manually.")
    $lines.Add("// Run: .\generate-schema-dbml.ps1 -Database fashion_shop")
    $lines.Add("")
    $lines.Add("Project Zestia_Fashion {")
    $lines.Add("  database_type: 'SQL Server'")
    $lines.Add("  Note: 'Cau truc CSDL thuc te cua he thong ban hang thoi trang Zestia'")
    $lines.Add("}")
    $lines.Add("")

    foreach ($tableGroup in ($columns | Group-Object schema_name, table_name)) {
        $first = $tableGroup.Group[0]
        $tableName = if ($first.schema_name -eq "dbo") { $first.table_name } else { "$($first.schema_name).$($first.table_name)" }
        $lines.Add("Table $tableName {")
        foreach ($column in $tableGroup.Group) {
            $attributes = [System.Collections.Generic.List[string]]::new()
            if ([int]$column.is_primary_key -eq 1) { $attributes.Add("pk") }
            if ([int]$column.is_identity -eq 1) { $attributes.Add("increment") }
            if ([int]$column.is_nullable -eq 0) { $attributes.Add("not null") }
            if ([int]$column.is_single_unique -eq 1) { $attributes.Add("unique") }
            if ($column.default_definition -ne [DBNull]::Value) {
                $default = ([string]$column.default_definition).Replace('`', '``')
                $attributes.Add("default: ``$default``")
            }
            $attributeText = if ($attributes.Count -gt 0) { " [" + ($attributes -join ", ") + "]" } else { "" }
            $lines.Add("  $($column.column_name) $(Convert-SqlTypeToDbml $column)$attributeText")
        }
        $lines.Add("}")
        $lines.Add("")
    }

    foreach ($foreignKey in $foreignKeys.Rows) {
        $childTable = if ($foreignKey.child_schema -eq "dbo") { $foreignKey.child_table } else { "$($foreignKey.child_schema).$($foreignKey.child_table)" }
        $parentTable = if ($foreignKey.parent_schema -eq "dbo") { $foreignKey.parent_table } else { "$($foreignKey.parent_schema).$($foreignKey.parent_table)" }
        $deleteOption = switch ([string]$foreignKey.delete_action) {
            "CASCADE" { " [delete: cascade]" }
            "SET_NULL" { " [delete: set null]" }
            "SET_DEFAULT" { " [delete: set default]" }
            default { "" }
        }
        $lines.Add("Ref $($foreignKey.fk_name): $childTable.$($foreignKey.child_column) > $parentTable.$($foreignKey.parent_column)$deleteOption")
    }

    $utf8NoBom = [System.Text.UTF8Encoding]::new($false)
    [System.IO.File]::WriteAllLines((Resolve-Path (Split-Path $OutputPath -Parent)).Path + "\" + (Split-Path $OutputPath -Leaf), $lines, $utf8NoBom)
    Write-Host "Generated $OutputPath from $Database ($($columns.Rows.Count) columns, $($foreignKeys.Rows.Count) foreign keys)."
}
finally {
    $connection.Dispose()
}
